#!/bin/sh

logger -t nvcheer "Update nvchecker service"
EXITCODE=0
for file in /etc/nvchecker/*.cfg; do
  source "${file}"
  logger -t nvchecker "Executing config file '${file}'"
  OUTPUT=$(
    i=0
    nvchecker "${nvchecker_folder}/nvchecker.ini" --logger json | while read -r line; do if [[ "${line}" == *update* ]]; then
      package_name=$(echo "${line}" | jq -r ".name")
      old_version=$(echo "${line}" | jq -r ".old_version")
      new_version=$(echo "${line}" | jq -r ".version")
      i=$((i + 1))
      echo "${i}: ${package_name} need update to ${new_version}."
    fi; done
  )
  logger -t nvchecker "${OUTPUT}"
  # if [[ "${OUTPUT}" != "" ]]; then
  #
  ## Send mail use Mailgun API
  #   curl -s --user 'api:YOUR_API_KEY' \
  #     https://api.mailgun.net/v3/example.com/messages \
  #     -F from='nvchecker <nvchecker@example.com>' \
  #     -F to=user@example.com \
  #     -F subject="nvchecker notification for ${file}" \
  #     -F text="${OUTPUT}"
  #
  ## or mutt
  #   echo "${OUTPUT}" | mutt -s "nvchecker notification" user@example.com -F /home/archlinux/.muttrc
  # fi
done
exit $EXITCODE
